# Generated by Django 4.1.5 on 2023-01-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article_author_name_article_author_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_article',
        ),
    ]
