# Generated by Django 4.1.5 on 2023-01-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
